# https://docs.travis-ci.com/user/languages/go/
language: go

# golang version to use
go:
- 1.8.x

# install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install curl unzip
  # protobuf 3.3.0
  - curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o protoc-3.3.0.zip
  - unzip protoc-3.3.0.zip -d $HOME/protoc
  # linter for .proto files
  - go get github.com/ckaznocha/protoc-gen-lint

# run main process
script:
  # check .proto files for style violations
  - $HOME/protoc/bin/protoc --lint_out=. *.proto
  
